[package]
name = "net_modeler"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
petgraph = "0.8.2"
serde = { version = "1.0.219", features = ["derive"] }
relm4 = "0.9.1"
relm4-components = "0.9.1"
rand= "0.9.1"
log = "0.4.27"
