[package]
name = "net_modeler"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
petgraph = "0.8.2"
serde = { version = "1.0.219", features = ["derive"] }
rand = "0.9.1"
log = "0.4.27"
raylib = { version = "5.5.1", features = ["imgui"] }
imgui = "0.12.0"
hashbrown = "0.16.0"
